# Generated by Django 4.2.1 on 2023-05-13 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_alter_team_teamtime'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='t_rank',
            field=models.IntegerField(default=0),
        ),
    ]
