# Generated by Django 4.2.1 on 2023-05-14 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_team_t_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='category',
            field=models.CharField(blank=True, choices=[('senior', 'senior'), ('junior', 'junior'), ('both', 'both')], max_length=10, null=True),
        ),
    ]
