# Generated by Django 4.2.1 on 2023-05-14 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_question_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
